# Generated by Django 5.0 on 2024-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
    ]
