# Generated by Django 5.0 on 2024-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_image_for_room_delete_teamimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image_for_room',
        ),
        migrations.AddField(
            model_name='team',
            name='image_for_team',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
