# Generated by Django 5.0 on 2024-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_team_image_for_room_team_image_for_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image_for_team',
            field=models.ImageField(blank=True, null=True, upload_to='team_media/'),
        ),
    ]
