# Generated by Django 5.0 on 2024-07-01 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('date_of_reservation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('number_of_beds', models.SmallIntegerField()),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Superior', 'Superior'), ('Double', 'Double'), ('Junior', 'Suite'), ('Family', 'Family')], max_length=20)),
                ('image_for_room', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
            ],
        ),
    ]
