# Generated by Django 5.0 on 2024-07-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_of_reservation']},
        ),
    ]
